### ISSUE TITLE
Simplify the tag 

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/highlightjs#2]
Thanks for the module! It works fine, but there is one inconvenience - currently we have to embed the code block with additional `<pre>` tag:

```
<pre><code class="[LANG]">
  // Code here...
</code></pre>
```

Is it possible to make it work with just:

```
<code class="[LANG]">
  // Code here...
</code>
```

?

**Comment by ghost** [comment]
That seems doable. According to highlight.js' [documentation](https://highlightjs.org/usage/), you can choose any tag(s) to mark up your code. We'd need to add an option to select the tag(s) used (to `/admin/config/content/highlightjs`, preferably with a select list of pre-defined options) and adjust the JS initialisation code appropriately.

PR's welcome!

**Comment by alanmels** [comment]
I've already re-configured my BuEditor to inject `<pre><code>` when pressed on the _code_ button, so will manage this way for now. Doubt I will have time soon, but if I will then I'll try to work on this and offer PR.

**Comment by ghost** [comment]
Here's a PR: https://github.com/backdrop-contrib/highlightjs/pull/4

**Comment by alanmels** [comment]
This is to report that if you set `<code>` in the module's settings, then both `<pre><code>` and `</code>` are covered. I've tested this using both tags in one post and both successfully got highlighted. You can just leave this as is just in case if there will be requests in the future to include other tags too. Or remove the `<pre><code>` which is covered anyway.

**Comment by ghost** [comment]
I hadn't considered this @alanmels, however I just tested it on my blog (where I first needed this module) and there's an issue with just using `<code>` tags...

Here's my [blog post](https://panda.id.au/posts/creating-a-node-programatically-in-backdrop) with highlightjs set to use `<pre><code>`:
![image](https://user-images.githubusercontent.com/2385329/105156208-9ed96480-5b5f-11eb-98c3-f0a3d6721f24.png)


And here's the same page but with highlightjs set to use just `<code>` tags:
![image](https://user-images.githubusercontent.com/2385329/105156516-10191780-5b60-11eb-96ce-bb257a009cec.png)

It seems that highlightjs will make whatever it highlights a block-level element, so (depending on your setup) this may not be desired.

I'll therefore leave this setting as-is, as it's useful in my situation at least. But thanks for brining it up.
