### ISSUE TITLE
Import more styles

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/highlightjs#5]
Comparing https://github.com/highlightjs/highlight.js/tree/master/src/styles with https://github.com/backdrop-contrib/highlightjs/tree/1.x-1.x/highlight.js/styles I see they've introduced number of newer styles. 

Wanted to offer a PR copying them all, however apparently the module needs them first to be minimized, so submitting this as a request. 

Thanks for consideration!

**Comment by alanmels** [comment]
I know there are tools like https://cssminifier.com, but afraid I have no extra time these days.

**Comment by ghost** [comment]
Thanks @alanmels. The above commit updates the included library to the latest version with all the new styles. I'll release a new version with this change.

And for future reference, as per https://github.com/backdrop-contrib/highlightjs/blob/1.x-1.x/highlight.js/BACKDROP.md, I use a different repo to get the minified styles, don't have to do them manually 🙂
